# Generated by Django 2.2.7 on 2019-12-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_auto_20191203_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
