# Generated by Django 2.2.7 on 2019-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dv',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
