# Generated by Django 2.2.7 on 2019-12-03 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_dv'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='movil',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
