# Generated by Django 2.2.7 on 2019-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20191203_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='esCliente',
            field=models.NullBooleanField(default=None),
        ),
    ]
