# Generated by Django 2.2.7 on 2019-12-03 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_escliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
